### PR TITLE
tf-next: Adds support for yarn workspaces

### LINKED ISSUE #93: Yarn workspace issue with node-fetch
Hey all,

Thanks for the great tool, when using this from a `yarn workspace` structured like the following:

```
root
 |  ...otherWorkspaces
 | web --> contains next, ...
```

When I run `cd web && yarn tf-next --skipDownload` and do a `terraform apply` I get the following error in the `PAGE_LAMBDA`:

```
2021-03-30T07:16:17.284Z	7dbd5f95-e964-4bd1-9ea0-ef2ddfd92413	ERROR	Unhandled error during request: Error: Cannot find module 'node-fetch'
Require stack:
- /var/task/node_modules/next/dist/next-server/server/node-polyfill-fetch.js
```

Is there some `noHoist` that I have to do to account for the workspace or me deploying from it?

EDIT: I've tried forcing `node-fetch` as a dep by using `noHoist` on it but now the error has moved on to the next dependency.

### PR DESCRIPTION
**Pull request by ofhouse**
Adds support for yarn workspaces to `tf-next build` command.

## ToDo
- [x] Make yarn workspace example working
   The thing is that we should should not change the original CWD (So entrypoint is always `/package.json` etc.), instead we should search for a yarn workspace root, and pass it as basedir when it exists.

Fixes #93.

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
Hmm, https://github.com/dealmore/terraform-aws-next-js/pull/107/checks?check_run_id=2279172762#step:6:810 seems like the failing tests seem related to them resolving to the correct directory but the base being different.

**Comment by ofhouse** [comment]
Yeah the issue is that the sub-directory of the package ends up as prefix in the route config. 🙈
So when the Next.js app is in a `packages/webapp/` directory, every route gets this prefix, e.g. `example.com/packages/webapp/`.

Will take another look soon. 😅

**Comment by JoviDeCroock** [comment]
Nice one, thank you for all the effort. Tried it out locally and the lambda is now reporting a 403 - Missing authentication token.

**Comment by ofhouse** [comment]
Yep, we currently only create `/__NEXT_PAGE_LAMBDA_0/{proxy+}` routes for the lambdas in the SAM template.
Unfortunately this does not cover the root route `/__NEXT_PAGE_LAMBDA_0/` since it has no proxy part.
Created an upstream issue in sammy: https://github.com/dealmore/sammy/issues/3

**Comment by ofhouse** [comment]
Okay, sammy is fixed now and now also supports index routes.
The issue itself is fixed when a more current version of next is used (was `9.1.4`).

**Comment by ofhouse** [comment]
lol, now another test is failing (╯°□°）╯︵ ┻━┻ 😅

**Comment by ofhouse** [comment]
Now released in [tf-next@0.7.0](https://www.npmjs.com/package/tf-next).

**Pull request merged**
