### PR TITLE
(fix) - use base argument in build

### PR DESCRIPTION
**Pull request by JoviDeCroock**
I guess one of the issues would be to now run yarn on the root in download mode? I guess this already makes `--skipDownload` work, but the complexity lies in the `tempDir` needing two package.json's I guess 😅

### CODE REVIEW

**Comment by ofhouse** [comment]
Yep, tried to wrap my head around the role of the download function yesterday.
The thing is that Vercel uses the identical build function (in runtime) to make it work, so my assumption is that nothing should be changed inside the runtime package to make it work.

However I tried it with different values for `workdir`, `entrypoint` and `repoRootPath` and never got a configuration that was working.
Need to take a closer look what Vercel is doing in this setup..

**Comment by JoviDeCroock** [comment]
Yes, so passing base should be sufficient I'd guess 😅 it's an interesting one, will def have a second look later

**Comment by JoviDeCroock** [comment]
@ofhouse

While digging through the code of vercel I found a good pointer:

```
    /**
     * The "Root Directory" is assigned to the `workPath` so the `repoRootPath`
     * is the Git Repository Root. This is only relevant for Monorepos.
     * See https://vercel.com/blog/monorepos
     */
    repoRootPath?: string;
```

**Comment by JoviDeCroock** [comment]
This also feels a bit odd when we're starting to use the `baseDir` https://github.com/dealmore/terraform-aws-next-js/blob/main/packages/runtime/src/index.ts#L1429

**Comment by ofhouse** [comment]
My guess is that the download function is used incorrectly here.
The variables itself should be set with the following values for the monorepo example:
```plain
entrypoint = '${tmpdir}/packages/web/package.json'
workPath = '${tmpdir}/packages/web'
repoRootPath = '${tmpdir}'
baseDir = repoRootPath;
```

I used the download function to download all the source files to the workPath, which is wrong here since the download function is only used at Vercel to download build cache.
The file copy itself (git clone) should take place outside of the runtime build I guess.

**Comment by JoviDeCroock** [comment]
I guess I'm coming to a similar conclusion as this is how the arguments look:

```
root /private/var/folders/hb/nt2jd3vs2s9_6b2wpcyktrp80000gn/T/tmp-41833-f6HGLZJne72c /var/folders/hb/nt2jd3vs2s9_6b2wpcyktrp80000gn/T/tmp-41847-dNKTTtFpy31N true
pkg /var/folders/hb/nt2jd3vs2s9_6b2wpcyktrp80000gn/T/tmp-41847-dNKTTtFpy31N/package.json
entry ../../../../../../../var/folders/hb/nt2jd3vs2s9_6b2wpcyktrp80000gn/T/tmp-41847-dNKTTtFpy31N/package.json
entryDir ../../../../../../../var/folders/hb/nt2jd3vs2s9_6b2wpcyktrp80000gn/T/tmp-41847-dNKTTtFpy31N
```

**Comment by ofhouse** [comment]
Ok, build is working now in #107 however the Lambda still produces an error when executed 🙈
Guess it will take another day until we solve it 😅

**Pull request closed without merging**
